import re

TEAM_NAME_MAP = {
    "Eintracht Frankfurt": "Eint Frankfurt",
    "Paris Saint-Germain": "Paris S-G",
    "Newcastle United": "Newcastle",
    "Tottenham Hotspur": "Tottenham",
    "Maccabi Tel Aviv FC": "Macc Tel Aviv",
    "Lincoln Red Imps FC": "Lincoln Imps",
    "Ħamrun Spartans FC": "Ħamrun Spartans",
    "Ludogorets Razgrad": "Ludogorets",
    "Nottingham Forest": "Nottm Forest",
    "Slovan Bratislava": "Slovan Bratisl",
    "Shakhtar Donetsk": "Shakhtar",
}

TEAM_BADGE_MAP = {
    "Aberdeen": "aberdeen.football-logos.cc.png",
    "AC Omonia": "omonoia.football-logos.cc.png",
    "AEK Athens": "aek-athens.football-logos.cc.png",
    "AEK Larnaca FC": "aek-larnaca.football-logos.cc.png",
    "Ajax": "ajax.football-logos.cc.png",
    "Alavés": "deportivo.football-logos.cc.png",
    "Angers": "angers.football-logos.cc.png",
    "Arsenal": "arsenal.football-logos.cc.png",
    "Aston Villa": "aston-villa.football-logos.cc.png",
    "Atalanta": "atalanta.football-logos.cc.png",
    "Athletic Club": "athletic-club.football-logos.cc.png",
    "Atlético Madrid": "atletico-madrid.football-logos.cc.png",
    "Augsburg": "augsburg.football-logos.cc.png",
    "Auxerre": "auxerre.football-logos.cc.png",
    "AZ Alkmaar": "az-alkmaar.football-logos.cc.png",
    "Barcelona": "barcelona.football-logos.cc.png",
    "Basel": "basel.football-logos.cc.png",
    "Bayern Munich": "bayern-munchen.football-logos.cc.png",
    "Benfica": "benfica.football-logos.cc.png",
    "BK Häcken": "hacken.football-logos.cc.png",
    "Bodø/Glimt": "bodo-glimt.football-logos.cc.png",
    "Bologna": "bologna.football-logos.cc.png",
    "Bournemouth": "bournemouth.football-logos.cc.png",
    "Braga": "sc-braga.football-logos.cc.png",
    "Brann": "brann.football-logos.cc.png",
    "Brentford": "brentford.football-logos.cc.png",
    "Breiðablik": "breidablik.football-logos.cc.png",
    "Brighton": "brighton.football-logos.cc.png",
    "Brest": "brest.football-logos.cc.png",
    "Burnley": "burnley.football-logos.cc.png",
    "Cagliari": "cagliari.football-logos.cc.png",
    "Celtic": "celtic.football-logos.cc.png",
    "Celta Vigo": "celta.football-logos.cc.png",
    "Chelsea": "chelsea.football-logos.cc.png",
    "Club Brugge": "club-brugge.football-logos.cc.png",
    "Como": "como-1907.football-logos.cc.png",
    "Cremonese": "cremonese.football-logos.cc.png",
    "Crystal Palace": "crystal-palace.football-logos.cc.png",
    "CS U Craiova": "u-craiova.football-logos.cc.png",
    "Dinamo Zagreb": "dinamo-zagreb.football-logos.cc.png",
    "Dortmund": "borussia-dortmund.football-logos.cc.png",
    "Dynamo Kyiv": "dynamo-kyiv.football-logos.cc.png",
    "Eintracht Frankfurt": "eintracht-frankfurt.football-logos.cc.png",
    "Elche": "elche.football-logos.cc.png",
    "Espanyol": "espanyol.football-logos.cc.png",
    "Everton": "everton.football-logos.cc.png",
    "FC Copenhagen": "copenhagen.football-logos.cc.png",
    "FC Kairat": "kairat.football-logos.cc.png",
    "FC Noah": "noah.football-logos.cc.png",
    "FCSB": "fcsb.football-logos.cc.png",
    "FK Shkëndija": "shkendija.football-logos.cc.png",
    "Fenerbahçe": "fenerbahce.football-logos.cc.png",
    "Ferencváros": "ferencvaros.football-logos.cc.png",
    "Feyenoord": "feyenoord.football-logos.cc.png",
    "Fiorentina": "fiorentina.football-logos.cc.png",
    "Freiburg": "freiburg.football-logos.cc.png",
    "Fulham": "fulham.football-logos.cc.png",
    "Galatasaray": "galatasaray.football-logos.cc.png",
    "Genk": "genk.football-logos.cc.png",
    "Genoa": "genoa.football-logos.cc.png",
    "Getafe": "getafe.football-logos.cc.png",
    "Girona": "girona.football-logos.cc.png",
    "Gladbach": "borussia-monchengladbach.football-logos.cc.png",
    "Go Ahead Eagles": "go-ahead-eagles.football-logos.cc.png",
    "Hamburger SV": "hamburger-sv.football-logos.cc.png",
    "Heidenheim": "fc-heidenheim.football-logos.cc.png",
    "Hellas Verona": "verona.football-logos.cc.png",
    "Hoffenheim": "hoffenheim.football-logos.cc.png",
    "Ħamrun Spartans FC": "hamrun-spartans.football-logos.cc.png",
    "Inter": "inter.football-logos.cc.png",
    "Jagiellonia": "jagiellonia.football-logos.cc.png",
    "Juventus": "juventus.football-logos.cc.png",
    "KF Drita": "drita.football-logos.cc.png",
    "Köln": "koln.football-logos.cc.png",
    "KuPS": "kups.football-logos.cc.png",
    "Lausanne-Sport": "lausanne-sport.football-logos.cc.png",
    "Lazio": "lazio.football-logos.cc.png",
    "Lecce": "lecce.football-logos.cc.png",
    "Lech Poznań": "lech-poznan.football-logos.cc.png",
    "Le Havre": "le-havre-ac.football-logos.cc.png",
    "Leeds United": "leeds-united.football-logos.cc.png",
    "Legia Warsaw": "legia-warszawa.football-logos.cc.png",
    "Lens": "rc-lens.football-logos.cc.png",
    "Levante": "levante.football-logos.cc.png",
    "Leverkusen": "bayer-leverkusen.football-logos.cc.png",
    "Lille": "lille.football-logos.cc.png",
    "Lincoln Red Imps FC": "lincoln-red-imps.football-logos.cc.png",
    "Liverpool": "liverpool.football-logos.cc.png",
    "Lorient": "lorient.football-logos.cc.png",
    "Ludogorets Razgrad": "ludogorets.football-logos.cc.png",
    "Lyon": "lyon.football-logos.cc.png",
    "Maccabi Tel Aviv FC": "m-tel-aviv.football-logos.cc.png",
    "Mainz 05": "mainz-05.football-logos.cc.png",
    "Mallorca": "mallorca.football-logos.cc.png",
    "Malmö":  "malmo.football-logos.cc.png",
    "Manchester City": "manchester-city.football-logos.cc.png",
    "Manchester Utd": "manchester-united.football-logos.cc.png",
    "Marseille": "marseille.football-logos.cc.png",
    "Metz": "fc-metz.football-logos.cc.png",
    "Midtjylland": "midtjylland.football-logos.cc.png",
    "Milan": "milan.football-logos.cc.png",
    "Monaco": "as-monaco.football-logos.cc.png",
    "Nantes": "nantes.football-logos.cc.png",
    "Napoli": "napoli.football-logos.cc.png",
    "Newcastle United": "newcastle.football-logos.cc.png",
    "Nice": "nice.football-logos.cc.png",
    "NK Celje": "celje.football-logos.cc.png",
    "Nottingham Forest": "nottingham-forest.football-logos.cc.png",
    "Olympiacos": "olympiacos.football-logos.cc.png",
    "Osasuna": "osasuna.football-logos.cc.png",
    "Oviedo": "oviedo.football-logos.cc.png",
    "PAOK": "paok.football-logos.cc.png",
    "Pafos FC": "pafos.football-logos.cc.png",
    "Panathinaikos": "panathinaikos.football-logos.cc.png",
    "Paris FC": "paris-fc.football-logos.cc.png",
    "Paris Saint-Germain": "paris-saint-germain.football-logos.cc.png",
    "Parma": "parma.football-logos.cc.png",
    "Pisa": "pisa.football-logos.cc.png",
    "Porto": "fc-porto.football-logos.cc.png",
    "PSV": "psv.football-logos.cc.png",
    "Qarabağ": "qarabag.football-logos.cc.png",
    "Raków": "rakow.football-logos.cc.png",
    "Rangers": "rangers.football-logos.cc.png",
    "Rapid Wien": "rapid-vienna.football-logos.cc.png",
    "Rayo Vallecano": "rayo-vallecano.football-logos.cc.png",
    "RB Leipzig": "rb-leipzig.football-logos.cc.png",
    "RB Salzburg": "salzburg.football-logos.cc.png",
    "Real Betis": "real-betis.football-logos.cc.png",
    "Real Madrid": "real-madrid.football-logos.cc.png",
    "Real Sociedad": "real-sociedad.football-logos.cc.png",
    "Red Star": "crvena-zvezda.football-logos.cc.png",
    "Rennes": "rennes.football-logos.cc.png",
    "Rijeka": "rijeka.football-logos.cc.png",
    "Roma": "roma.football-logos.cc.png",
    "Samsunspor": "samsunspor.football-logos.cc.png",
    "Sassuolo": "sassuolo.football-logos.cc.png",
    "Sevilla": "sevilla.football-logos.cc.png",
    "Shakhtar Donetsk": "shakhtar.football-logos.cc.png",
    "Shamrock Rovers": "shamrock-rovers.football-logos.cc.png",
    "Shelbourne FC": "shelbourne.football-logos.cc.png",
    "Sigma Olomouc": "olomouc.football-logos.cc.png",
    "Slavia Prague": "slavia-praha.football-logos.cc.png",
    "Slovan Bratislava": "s-bratislava.football-logos.cc.png",
    "Sporting CP": "sporting-cp.football-logos.cc.png",
    "Sparta Prague": "sparta-praha.football-logos.cc.png",
    "Strasbourg": "rc-strasbourg-alsace.football-logos.cc.png",
    "St Pauli": "st-pauli.football-logos.cc.png",
    "Sturm Graz": "sturm-graz.football-logos.cc.png",
    "Stuttgart": "vfb-stuttgart.football-logos.cc.png",
    "Sunderland": "sunderland.football-logos.cc.png",
    "Tottenham Hotspur": "tottenham.football-logos.cc.png",
    "Toulouse": "toulouse.football-logos.cc.png",
    "Torino": "torino.football-logos.cc.png",
    "Udinese": "udinese.football-logos.cc.png",
    "Union Berlin": "union-berlin.football-logos.cc.png",
    "Union SG": "union-saint-gilloise.football-logos.cc.png",
    "Utrecht": "fc-utrecht.football-logos.cc.png",
    "Valencia": "valencia.football-logos.cc.png",
    "Viktoria Plzeň": "viktoria-plzen.football-logos.cc.png",
    "Villarreal": "villarreal.football-logos.cc.png",
    "Werder Bremen": "werder-bremen.football-logos.cc.png",
    "West Ham United": "west-ham.football-logos.cc.png",
    "Wolfsburg": "wolfsburg.football-logos.cc.png",
    "Wolves": "wolves.football-logos.cc.png",
    "Young Boys": "young-boys.football-logos.cc.png",
    "Zrinjski Mostar": "zrinjski.football-logos.cc.png"
}

def map_team_name(db_name: str) -> str:
    return TEAM_NAME_MAP.get(db_name, db_name)

def map_team_logo_path(db_name: str) -> str:
    return TEAM_BADGE_MAP.get(db_name, db_name)

def map_us_team_logo_path(db_name: str) -> str:
    return re.sub(r'[^a-z0-9_]', '', db_name.lower().replace(' ', '_')) + '_logo_primary.png'