from .settings import config
from .leagues import UEFA_LEAGUE_MAPPING, UEFA_LEAGUE_REVERSE_MAPPING, UEFA_LEAGUE_ORDER

__all__ = ['config', 'UEFA_LEAGUE_MAPPING', 'UEFA_LEAGUE_REVERSE_MAPPING', 'UEFA_LEAGUE_ORDER']